import { Injectable } from '@angular/core';
import {Country} from './country';
@Injectable({
    providedIn: 'root'
})
export class CountryService{
    getCountries():Country[]{
        let countries=[
            new Country('AF','Afghanistan'),
new Country('AL','Albania'),
new Country('DZ','Algeria'),
new Country('AS','American Samoa'),
new Country('AD','Andorra'),
new Country('AG','Angola'),
new Country('AI','Anguilla'),
new Country('AG','Antigua &amp; Barbuda'),
new Country('AR','Argentina'),
new Country('AA','Armenia'),
new Country('AW','Aruba'),
new Country('AU','Australia'),
new Country('AT','Austria'),
new Country('AZ','Azerbaijan'),
new Country('BS','Bahamas'),
new Country('BH','Bahrain'),
new Country('BD','Bangladesh'),
new Country('BB','Barbados'),
new Country('BY','Belarus'),
new Country('BE','Belgium'),
new Country('BZ','Belize'),
new Country('BJ','Benin'),
new Country('BM','Bermuda'),
new Country('BT','Bhutan'),
new Country('BO','Bolivia'),
new Country('BL','Bonaire'),
new Country('BA','Bosnia &amp; Herzegovina'),
new Country('BW','Botswana'),
new Country('BR','Brazil'),
new Country('BC','British Indian Ocean Ter'),
new Country('BN','Brunei'),
new Country('BG','Bulgaria'),
new Country('BF','Burkina Faso'),
new Country('BI','Burundi'),
new Country('KH','Cambodia'),
new Country('CM','Cameroon'),
new Country('CA','Canada'),
new Country('IC','Canary Islands'),
new Country('CV','Cape Verde'),
new Country('KY','Cayman Islands'),
new Country('CF','Central African Republic'),
new Country('TD','Chad'),
new Country('CD','Channel Islands'),
new Country('CL','Chile'),
new Country('CN','China'),
new Country('CI','Christmas Island'),
new Country('CS','Cocos Island'),
new Country('CO','Colombia'),
new Country('CC','Comoros'),
new Country('CG','Congo'),
new Country('CK','Cook Islands'),
new Country('CR','Costa Rica'),
new Country('CT','Cote D\'Ivoire'),
new Country('HR','Croatia'),
new Country('CU','Cuba'),
new Country('CB','Curacao'),
new Country('CY','Cyprus'),
new Country('CZ','Czech Republic'),
new Country('DK','Denmark'),
new Country('DJ','Djibouti'),
new Country('DM','Dominica'),
new Country('DO','Dominican Republic'),
new Country('TM','East Timor'),
new Country('EC','Ecuador'),
new Country('EG','Egypt'),
new Country('SV','El Salvador'),
new Country('GQ','Equatorial Guinea'),
new Country('ER','Eritrea'),
new Country('EE','Estonia'),
new Country('ET','Ethiopia'),
new Country('FA','Falkland Islands'),
new Country('FO','Faroe Islands'),
new Country('FJ','Fiji'),
new Country('FI','Finland'),
new Country('FR','France'),
new Country('GF','French Guiana'),
new Country('PF','French Polynesia'),
new Country('FS','French Southern Ter'),
new Country('GA','Gabon'),
new Country('GM','Gambia'),
new Country('GE','Georgia'),
new Country('DE','Germany'),
new Country('GH','Ghana'),
new Country('GI','Gibraltar'),
new Country('GB','Great Britain'),
new Country('GR','Greece'),
new Country('GL','Greenland'),
new Country('GD','Grenada'),
new Country('GP','Guadeloupe'),
new Country('GU','Guam'),
new Country('GT','Guatemala'),
new Country('GN','Guinea'),
new Country('GY','Guyana'),
new Country('HT','Haiti'),
new Country('HW','Hawaii'),
new Country('HN','Honduras'),
new Country('HK','Hong Kong'),
new Country('HU','Hungary'),
new Country('IS','Iceland'),
new Country('IN','India'),
new Country('ID','Indonesia'),
new Country('IA','Iran'),
new Country('IQ','Iraq'),
new Country('IR','Ireland'),
new Country('IM','Isle of Man'),
new Country('IL','Israel'),
new Country('IT','Italy'),
new Country('JM','Jamaica'),
new Country('JP','Japan'),
new Country('JO','Jordan'),
new Country('KZ','Kazakhstan'),
new Country('KE','Kenya'),
new Country('KI','Kiribati'),
new Country('NK','Korea North'),
new Country('KS','Korea South'),
new Country('KW','Kuwait'),
new Country('KG','Kyrgyzstan'),
new Country('LA','Laos'),
new Country('LV','Latvia'),
new Country('LB','Lebanon'),
new Country('LS','Lesotho'),
new Country('LR','Liberia'),
new Country('LY','Libya'),
new Country('LI','Liechtenstein'),
new Country('LT','Lithuania'),
new Country('LU','Luxembourg'),
new Country('MO','Macau'),
new Country('MK','Macedonia'),
new Country('MG','Madagascar'),
new Country('MY','Malaysia'),
new Country('MW','Malawi'),
new Country('MV','Maldives'),
new Country('ML','Mali'),
new Country('MT','Malta'),
new Country('MH','Marshall Islands'),
new Country('MQ','Martinique'),
new Country('MR','Mauritania'),
new Country('MU','Mauritius'),
new Country('ME','Mayotte'),
new Country('MX','Mexico'),
new Country('MI','Midway Islands'),
new Country('MD','Moldova'),
new Country('MC','Monaco'),
new Country('MN','Mongolia'),
new Country('MS','Montserrat'),
new Country('MA','Morocco'),
new Country('MZ','Mozambique'),
new Country('MM','Myanmar'),
new Country('NA','Nambia'),
new Country('NU','Nauru'),
new Country('NP','Nepal'),
new Country('AN','Netherland Antilles'),
new Country('NL','Netherlands (Holland, Europe)'),
new Country('NV','Nevis'),
new Country('NC','New Caledonia'),
new Country('NZ','New Zealand'),
new Country('NI','Nicaragua'),
new Country('NE','Niger'),
new Country('NG','Nigeria'),
new Country('NW','Niue'),
new Country('NF','Norfolk Island'),
new Country('NO','Norway'),
new Country('OM','Oman'),
new Country('PK','Pakistan'),
new Country('PW','Palau Island'),
new Country('PS','Palestine'),
new Country('PA','Panama'),
new Country('PG','Papua New Guinea'),
new Country('PY','Paraguay'),
new Country('PE','Peru'),
new Country('PH','Philippines'),
new Country('PO','Pitcairn Island'),
new Country('PL','Poland'),
new Country('PT','Portugal'),
new Country('PR','Puerto Rico'),
new Country('QA','Qatar'),
new Country('ME','Republic of Montenegro'),
new Country('RS','Republic of Serbia'),
new Country('RE','Reunion'),
new Country('RO','Romania'),
new Country('RU','Russia'),
new Country('RW','Rwanda'),
new Country('NT','St Barthelemy'),
new Country('EU','St Eustatius'),
new Country('HE','St Helena'),
new Country('KN','St Kitts-Nevis'),
new Country('LC','St Lucia'),
new Country('MB','St Maarten'),
new Country('PM','St Pierre &amp; Miquelon'),
new Country('VC','St Vincent &amp; Grenadines'),
new Country('SP','Saipan'),
new Country('SO','Samoa'),
new Country('AS','Samoa American'),
new Country('SM','San Marino'),
new Country('ST','Sao Tome &amp; Principe'),
new Country('SA','Saudi Arabia'),
new Country('SN','Senegal'),
new Country('RS','Serbia'),
new Country('SC','Seychelles'),
new Country('SL','Sierra Leone'),
new Country('SG','Singapore'),
new Country('SK','Slovakia'),
new Country('SI','Slovenia'),
new Country('SB','Solomon Islands'),
new Country('OI','Somalia'),
new Country('ZA','South Africa'),
new Country('ES','Spain'),
new Country('LK','Sri Lanka'),
new Country('SD','Sudan'),
new Country('SR','Suriname'),
new Country('SZ','Swaziland'),
new Country('SE','Sweden'),
new Country('CH','Switzerland'),
new Country('SY','Syria'),
new Country('TA','Tahiti'),
new Country('TW','Taiwan'),
new Country('TJ','Tajikistan'),
new Country('TZ','Tanzania'),
new Country('TH','Thailand'),
new Country('TG','Togo'),
new Country('TK','Tokelau'),
new Country('TO','Tonga'),
new Country('TT','Trinidad &amp; Tobago'),
new Country('TN','Tunisia'),
new Country('TR','Turkey'),
new Country('TU','Turkmenistan'),
new Country('TC','Turks &amp; Caicos Is'),
new Country('TV','Tuvalu'),
new Country('UG','Uganda'),
new Country('UA','Ukraine'),
new Country('AE','United Arab Emirates'),
new Country('GB','United Kingdom'),
new Country('US','United States of America'),
new Country('UY','Uruguay'),
new Country('UZ','Uzbekistan'),
new Country('VU','Vanuatu'),
new Country('VS','Vatican City State'),
new Country('VE','Venezuela'),
new Country('VN','Vietnam'),
new Country('VB','Virgin Islands (Brit)'),
new Country('VA','Virgin Islands (USA)'),
new Country('WK','Wake Island'),
new Country('WF','Wallis &amp; Futana Is'),
new Country('YE','Yemen'),
new Country('ZR','Zaire'),
new Country('ZM','Zambia'),
new Country('ZW','Zimbabwe'),
        ]
        return countries;
    }
}